### ISSUE TITLE
feat : An event Schedule section should be added. 

### ISSUE THREAD

**Issue by ElegantFalcon** [FossMec/deb-utsav#1]
## Current Behavior
No event schedule section.

## Expected Behavior 
An event schedule section should be included , highlighting the dates and allocated time for each speaker, among other relevant details.

## Screenshots/ Mockups
![image](https://github.com/FossMec/deb-utsav/assets/109782243/24d90590-7d4f-42e5-b5a4-0129e36b3cc6)

**Comment by urveshgodhani** [comment]
i am interested to implement this task

**Comment by ElegantFalcon** [comment]
The feature has been implemented.

**Comment by ElegantFalcon** [comment]
> i am interested to implement this task


The feature has been implemented.
