### ISSUE TITLE
feat: Speakers section on navbar

### ISSUE THREAD

**Issue by roshinjimmy** [FossMec/deb-utsav#4]
## Current Behaviour
No Speakers section on the navbar

## Desired Behaviour
A Speakers section should be added on the navbar which links to the Speakers section on the Home page

## Screenshots/Mockups
![Speakers section](https://github.com/FossMec/deb-utsav/assets/120731728/ac11ff13-cfd1-45a0-9fcc-192a121ac93a)

**Comment by n1ved** [comment]
I'm interested to work on this , Can you assign this to  me ?

**Comment by foss-cell-mec** [comment]
Yes!
Fork the repo and submit a pr. You can do it in the main branch. @n1ved

**Comment by n1ved** [comment]
I have doubt regarding in which position new menu item should  I put it after 'schedule' section ?
![image](https://github.com/FossMec/deb-utsav/assets/42319263/9711cd51-52da-4713-ae10-b5f61611950c)

**Comment by n1ved** [comment]
I have opened a pr #7
